apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cd-generator
  namespace: default
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/captain-valross/argo_test
        revision: main
        files:
          - path: 'config/*.yaml'

  template:
    metadata:
      name: 'argo-{{ .cluster }}'
    spec:
      source:
        repoURL: https://github.com/captain-valross/argo_test
        targetRevision: HEAD
        path: helm
        helm:
          valueFiles:
            - '../config/{{ .path.filename }}'
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd-{{ .cluster }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
